Algoritmo "correçãoAtividadeAula1"

Var
numero, antecessor : INTEIRO

Inicio
// 1) Escreva um algoritmo para ler um valor e escrever seu antecessor
// ENTRADA
// RECEBER UM NÚMERO
escreval("Digite um número para verificar antecessor: ")
leia(numero)

// PROCESSO
// NUMERO - 1
antecessor <- numero - 1

// SAIDA
// ESCREVER O ANTECESSOR
limpaTela
escreval("O antecessor do numero ",numero," é ",antecessor)

Fimalgoritmo